### ISSUE TITLE
Carthage installation failed

### ISSUE THREAD

**Issue by mokumoku** [crexista/KabuKit#38]
`$ carthage bootstrap --platform iOS` build failed.

```
*** Building scheme "KabuKit" in KabuKit.xcodeproj
** BUILD FAILED **


The following build commands failed:
        PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock Build/Intermediates/KabuKit.build/Release-iphoneos/KabuKit.build/Script-4D286322F4FD3E46231E45CD.sh
(1 failure)
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
A shell task (/usr/bin/xcrun xcodebuild -project /path/to/carthage/Carthage/Checkouts/KabuKit/KabuKit.xcodeproj -scheme KabuKit -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **
```

I found `KabuKit` has two shared scheme for iOS platform

![2017-01-13 20 33 35](https://cloud.githubusercontent.com/assets/3917725/21928772/0c6fcacc-d9d0-11e6-95e5-cc92551fc837.png)

Why `KabuKit` scheme are duplicated?
Shared `KabuKit` scheme conflicts with `KabuKit-iOS` scheme when fetching via Carthage.
To fix carthage build, delete or configure some settings shared `KabuKit` scheme.

**Comment by crexista** [comment]
> Why KabuKit scheme are duplicated?

I don't know.
I'm sorry that may be my mistake.
I think that there no problem delete duplicated `Kabukit` scheme.

**Comment by crexista** [comment]
I pulled this repository newly and I checked project file on master branch.
![2017-01-16 14 56 35](https://cloud.githubusercontent.com/assets/1249559/21972312/0e760b82-dbfc-11e6-9155-adb4f8a52591.png)

Scheme `KabuKit` is not duplecated.
Please pull try again
