### ISSUE TITLE
Destination.StageType is always UIViewController?

### ISSUE THREAD

**Issue by mokumoku** [crexista/KabuKit#48]
To create `typealias StageType` every view controller is redundant, I think.

```
public protocol SceneLinkage : SceneRouter {
    public func guide(to destination: Self.DestinationType) -> KabuKit.SceneTransition<Self.DestinationType.StageType>?
}
```

to

```
public protocol SceneLinkage : SceneRouter {
    public func guide(to destination: Self.DestinationType) -> KabuKit.SceneTransition<UIViewController>?
}
```

**Comment by crexista** [comment]
My answer for your question`Destination.StageType is always UIViewController?` is NO;
`Stage` is container that contain all view object in a scene.
So, `Stage` may be`UIViewController` or sometimes `UIView` or sometime anything else.

But, I have no choice but to agree your opinion that creating typealias StageType every view controller is redundant.

So, I will reconsider relationship between `DestinationType` and `StageType`

**Comment by crexista** [comment]
@mokumoku sorry, this I/F is changed significantly at ver 0.3.0.
So, I close this issue. 🙇
